### ISSUE TITLE
Occationally doesn't work with Dydx orders

### ISSUE THREAD

**Issue by vindberg** [Algobadger/Starkex#1]
Hello and thanks for creating this port of the Starkex signing logic.

Im trying to use it (currently on Georli Testnet) - Is there any reason why it would sometimes stop working. E.g. first 4 orders goes with success and then afterwards (same Order size and everything (even expiration timestamp)) it fails with the "Invalid signature for order" message.

Any ideas are most helpful. Thanks.

**Comment by vindberg** [comment]
@sakib1361 Are you getting notifications from github? Just wondering if you saw my message? :)

**Comment by sakib1361** [comment]
Sorry didnt see the messages, 
Can create a test app to see if it works on a test market. Currently I still didn't test high speed orders. 
The library should be stateless.

**Comment by vindberg** [comment]
Hi, thanks for getting back to me. I found another solution now. Have a good day.
